### ISSUE TITLE
Implement new group of 5 Export Functions - wink

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-IM01#6]
Please can you implement the following family of (5) functions based on a 'wink':

a 'wink' is a one-off signal - brief, easy to miss, a bit subtle.  The light flashes on once then off.

1 - for beginners please implement 2 simple functions:

**wink blue** 
**wink green**

No parameters.
Turn on LED to blue / green at medium (50pc) intensity for 250ms (do these parms sound OK?)

WHY these functions?  
With no params at all they are suited for schools kids aged 8 - this might be the first time they use a peripheral. And convenient for anyone. Just easy to use :)

2 - **wink(int)**

**wink blue for [int] milliseconds**
**wink green for [int] milliseconds**

Two functions - one for blue and one for green:
… input param is an integer - milliseconds.  Duration for which the light is on.

3 - **wink (int blue)(int green) for (int duration) milliseconds**
… blue param is blue component of the light - slide control from 0 to 255
… green param is green component of the light - slide control from 0 to 255
… duration param - duration of wink.  Slide control from 50 to 1000

NOTE: use the 'compartmentisalation' feature of MakeCode - set them up as a group so that these five blocks above are a set of functions grouped under the heading 'wink'.

**Comment by KalbeAbbas** [comment]
For the first two functions duration of 500 ms seems better. I have set with 500ms
